# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dlg_About(object):
    def setupUi(self, Dlg_About):
        Dlg_About.setObjectName("Dlg_About")
        Dlg_About.resize(453, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dlg_About.sizePolicy().hasHeightForWidth())
        Dlg_About.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dlg_About.setFont(font)
        self.graphicsView = QtWidgets.QGraphicsView(Dlg_About)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setAcceptDrops(False)
        self.graphicsView.setStyleSheet("border-image: url(:/SDPW.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Dlg_About)
        self.label.setGeometry(QtCore.QRect(131, 30, 115, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: Arial; font-size: 18px ")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dlg_About)
        self.label_2.setGeometry(QtCore.QRect(131, 66, 248, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dlg_About)
        self.label_3.setGeometry(QtCore.QRect(130, 91, 248, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dlg_About)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 322, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dlg_About)
        self.label_5.setGeometry(QtCore.QRect(130, 160, 304, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dlg_About)
        self.label_6.setGeometry(QtCore.QRect(130, 200, 304, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_6.setObjectName("label_6")
        self.label_ver = QtWidgets.QLabel(Dlg_About)
        self.label_ver.setGeometry(QtCore.QRect(253, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_ver.setFont(font)
        self.label_ver.setStyleSheet("font-family: Arial; font-size: 14px ")
        self.label_ver.setObjectName("label_ver")

        self.retranslateUi(Dlg_About)
        QtCore.QMetaObject.connectSlotsByName(Dlg_About)

    def retranslateUi(self, Dlg_About):
        _translate = QtCore.QCoreApplication.translate
        Dlg_About.setWindowTitle(_translate("Dlg_About", "About SDP Wizard"))
        self.label.setText(_translate("Dlg_About", "SDP Wizard"))
        self.label_2.setText(_translate("Dlg_About", "Build SDP files for Harmonic Spectrum,"))
        self.label_3.setText(_translate("Dlg_About", "Simpler and without typo."))
        self.label_4.setText(_translate("Dlg_About", "For Spectrum only, other usages are not verified."))
        self.label_5.setText(_translate("Dlg_About", "Make sure take manual review carefully!"))
        self.label_6.setText(_translate("Dlg_About", "Report bugs to Charles.Sun@harmonicinc.com"))
        self.label_ver.setText(_translate("Dlg_About", "Ver. 0.5.1 Beta"))
import resource_rc
